---
book:
  type: document
  height: 297mm #mm
  width: 210mm #mm
  bleed: 3mm #mm fond perdu
  Tmargin: 20mm #mm
  Bmargin: 20mm #mm
  Lmargin: 15mm #mm
  Rmargin: 15mm #mm
  Imargin: 15mm #mm Marge intérieure (si double page)
  Emargin: 10mm #mm Marge extérieure (si double page)