import { IDML } from "../IDML";
import type { XMLObjet } from "../types/types";
import { AbstractFileClass } from "./AbstractFileClass";

export class Styles extends AbstractFileClass {
  protected Name = 'Styles';
  protected folder = 'Resources';
  protected bookProperty = 'styles';

  /**
   * Pas besoin de fichier si aucune donnée styles n'est définie
   */
  protected override buildMinimalFile(contentNone?: XMLObjet) {
    return ;
  }
}

/**
 * Toutes les données des propriétés des styles
 * (ça ne sert à rien pour le moment)
 */
const DATA_PROPS = {
  children: [
    {
      tag: 'RootCharacterStyleGroup',
      childTag: 'CharacterStyle',
      children: [
        // No character par défaut
        {
          attrs: [
            ['Self', 'CharacterStyle/$ID/[No character style]'],
            ['Imported', 'false'],
            ['SplitDocument', 'false'],
            ['EmitCss', 'true'],
            ['StyleUniqueId', '3295eefb-54fd-4e4d-a7c1-a4481c517dc3'],
            ['IncludeClass', 'true'],
            ['ExtendedKeyboardShortcut', '0 0 0'],
            ['Name', '$ID/[No character style]']]
        },
      ],
      childDefaultAttrs: {},
      attrs: [['Self', IDML.generateId()]]
    },
    {
      tag: 'RootParagraphStyleGroup',
      childTag: 'ParagraphStyle',
      children: [
        // Style "no paragraph style" (par défaut)
        {
          attrs: [
            ['Self', "ParagraphStyle/$ID/[No paragraph style]"],
            ['Name', "$ID/[No paragraph style]"],
            ['Imported', 'false'],
            ['SplitDocument', 'false'],
            ['EmitCss', 'true'],
            ['StyleUniqueId', '7173ae8f-0f4a-4533-80bf-85e3b1b6fede'],
            ['IncludeClass', 'true'],
            ['ExtendedKeyboardShortcut', '0 0 0'],
            ['EmptyNestedStyles', 'true'],
            ['EmptyLineStyles', 'true'],
            ['EmptyGrepStyles', 'true'],
            ['FillColor', "Color/Black"],
            ['FontStyle', 'Regular'],
            ['PointSize', '12'],
            ['HorizontalScale', '100'],
            ['KerningMethod', '$ID/Metrics'],
            ['Ligatures', 'true'],
            ['PageNumberType', 'AutoPageNumber'],
            ['StrokeWeight', '1'],
            ['Tracking', '0'],
            ['Composer', 'HL Composer'],
            ['DropCapCharacters', '0'],
            ['DropCapLines', '0'],
            ['BaselineShift', '0'],
            ['Capitalization', 'Normal'],
            ['StrokeColor', 'Swatch/None'],
            ['HyphenateLadderLimit', '3'],
            ['VerticalScale', '100'],
            ['LeftIndent', '0'],
            ['RightIndent', '0'],
            ['FirstLineIndent', '0'],
            ['AutoLeading', '120'],
            ['AppliedLanguage', '$ID/French: FR'],
            ['Hyphenation', 'true'],
            ['HyphenateAfterFirst', '2'],
            ['HyphenateBeforeLast', '2'],
            ['HyphenateCapitalizedWords', 'true'],
            ['HyphenateWordsLongerThan', '5'],
            ['NoBreak', 'false'],
            ['HyphenationZone', '36'],
            ['SpaceBefore', '0'],
            ['SpaceAfter', 0],
            ['Underline', false],
            ['OTFFigureStyle', 'default'],
            ['DesiredWordSpacing', 100],
            ['MaximumWordSpacing', 133],
            ['MinimumWordSpacing', 80],
            ['DesiredLetterSpacing', 0],
            ['MaximumLetterSpacing', 0],
            ['MinimumLetterSpacing', 0],
            ['DesiredGlyphScaling', 100],
            ['MaximumGlyphScaling', 100],
            ['MinimumGlyphScaling', 100],
            ['StartParagraph', 'Anywhere'],
            ['KeepAllLinesTogether', false],
            ['KeepWithNext', 0],
            ['KeepFirstLines', 2],
            ['KeepLastLines', 2],
            ['Position', 'Normal'],
            ['StrikeThru', false],
            ['CharacterAlignment', 'AlignEmCenter'],
            ['KeepLinesTogether', false],
            ['StrokeTint', -1],
            ['FillTint', -1],
            ['OverprintStroke', false],
            ['OverprintFill', false],
            ['GradientStrokeAngle', 0],
            ['GradientFillAngle', 0],
            ['GradientStrokeLength', -1],
            ['GradientFillLength', -1],
            ['GradientStrokeStart', '0 0'],
            ['GradientFillStart', '0 0'],
            ['Skew', 0],
            ['RuleAboveLineWeight', 1],
            ['RuleAboveTint', -1],
            ['RuleAboveOffset', 0],
            ['RuleAboveLeftIndent', 0],
            ['RuleAboveRightIndent', 0],
            ['RuleAboveWidth', 'ColumnWidth'],
            ['RuleBelowLineWeight', 1],
            ['RuleBelowTint', -1],
            ['RuleBelowOffset', 0],
            ['RuleBelowLeftIndent', 0],
            ['RuleBelowRightIndent', 0],
            ['RuleBelowWidth', 'ColumnWidth'],
            ['RuleAboveOverprint', false],
            ['RuleBelowOverprint', false],
            ['RuleAbove', false],
            ['RuleBelow', false],
            ['LastLineIndent', 0],
            ['HyphenateLastWord', true],
            ['ParagraphBreakType', 'Anywhere'],
            ['SingleWordJustification', 'FullyJustified'],
            ['OTFOrdinal', false],
            ['OTFFraction', false],
            ['OTFDiscretionaryLigature', false],
            ['OTFTitling', false],
            ['RuleAboveGapTint', -1],
            ['RuleAboveGapOverprint', false],
            ['RuleBelowGapTint', -1],
            ['RuleBelowGapOverprint', false],
            ['Justification', 'LeftAlign'],
            ['DropcapDetail', 1],
            ['PositionalForm', 'None'],
            ['OTFMark', true],
            ['HyphenWeight', 5],
            ['OTFLocale', true],
            ['HyphenateAcrossColumns', true],
            ['KeepRuleAboveInFrame', false],
            ['IgnoreEdgeAlignment', false],
            ['OTFSlashedZero', false],
            ['OTFStylisticSets', 0],
            ['OTFHistorical', false],
            ['OTFContextualAlternate', true],
            ['UnderlineGapOverprint', false],
            ['UnderlineGapTint', -1],
            ['UnderlineOffset', -9999],
            ['UnderlineOverprint', false],
            ['UnderlineTint', -1],
            ['UnderlineWeight', -9999],
            ['StrikeThroughGapOverprint', false],
            ['StrikeThroughGapTint', -1],
            ['StrikeThroughOffset', -9999],
            ['StrikeThroughOverprint', false],
            ['StrikeThroughTint', -1],
            ['StrikeThroughWeight', -9999],
            ['MiterLimit', 4],
            ['StrokeAlignment', 'OutsideAlignment'],
            ['EndJoin', 'MiterEndJoin'],
            ['SpanColumnType', 'SingleColumn'],
            ['SplitColumnInsideGutter', 6],
            ['SplitColumnOutsideGutter', 0],
            ['KeepWithPrevious', false],
            ['SpanColumnMinSpaceBefore', 0],
            ['SpanColumnMinSpaceAfter', 0],
            ['OTFSwash', false],
            ['ParagraphShadingTint', 20],
            ['ParagraphShadingOverprint', false],
            ['ParagraphShadingWidth', 'ColumnWidth'],
            ['ParagraphShadingOn', false],
            ['ParagraphShadingClipToFrame', false],
            ['ParagraphShadingSuppressPrinting', false],
            ['ParagraphShadingLeftOffset', 0],
            ['ParagraphShadingRightOffset', 0],
            ['ParagraphShadingTopOffset', 0],
            ['ParagraphShadingBottomOffset', 0],
            ['ParagraphShadingTopOrigin', 'AscentTopOrigin'],
            ['ParagraphShadingBottomOrigin', 'DescentBottomOrigin'],
            ['ParagraphBorderTint', -1],
            ['ParagraphBorderOverprint', false],
            ['ParagraphBorderOn', false],
            ['ParagraphBorderGapTint', -1],
            ['ParagraphBorderGapOverprint', false],
            ['Tsume', 0],
            ['LeadingAki', -1],
            ['TrailingAki', -1],
            ['KinsokuType', 'KinsokuPushInFirst'],
            ['KinsokuHangType', 'None'],
            ['BunriKinshi', true],
            ['RubyOpenTypePro', true],
            ['RubyFontSize', -1],
            ['RubyAlignment', 'RubyJIS'],
            ['RubyType', 'PerCharacterRuby'],
            ['RubyParentSpacing', 'RubyParent121Aki'],
            ['RubyXScale', 100],
            ['RubyYScale', 100],
            ['RubyXOffset', 0],
            ['RubyYOffset', 0],
            ['RubyPosition', 'AboveRight'],
            ['RubyAutoAlign', true],
            ['RubyParentOverhangAmount', 'RubyOverhangOneRuby'],
            ['RubyOverhang', false],
            ['RubyAutoScaling', false],
            ['RubyParentScalingPercent', 66],
            ['RubyTint', -1],
            ['RubyOverprintFill', 'Auto'],
            ['RubyStrokeTint', -1],
            ['RubyOverprintStroke', 'Auto'],
            ['RubyWeight', -1],
            ['KentenKind', 'None'],
            ['KentenFontSize', -1],
            ['KentenXScale', 100],
            ['KentenYScale', 100],
            ['KentenPlacement', 0],
            ['KentenAlignment', 'AlignKentenCenter'],
            ['KentenPosition', 'AboveRight'],
            ['KentenCustomCharacter', ''],
            ['KentenCharacterSet', 'CharacterInput'],
            ['KentenTint', -1],
            ['KentenOverprintFill', 'Auto'],
            ['KentenStrokeTint', -1],
            ['KentenOverprintStroke', 'Auto'],
            ['KentenWeight', -1],
            ['Tatechuyoko', false],
            ['TatechuyokoXOffset', 0],
            ['TatechuyokoYOffset', 0],
            ['AutoTcy', 0],
            ['AutoTcyIncludeRoman', false],
            ['Jidori', 0],
            ['GridGyoudori', 0],
            ['GridAlignFirstLineOnly', false],
            ['GridAlignment', 'None'],
            ['CharacterRotation', 0],
            ['RotateSingleByteCharacters', false],
            ['Rensuuji', true],
            ['ShataiMagnification', 0],
            ['ShataiDegreeAngle', 4500],
            ['ShataiAdjustTsume', true],
            ['ShataiAdjustRotation', false],
            ['Warichu', false],
            ['WarichuLines', 2],
            ['WarichuSize', 50],
            ['WarichuLineSpacing', 0],
            ['WarichuAlignment', 'Auto'],
            ['WarichuCharsBeforeBreak', 2],
            ['WarichuCharsAfterBreak', 2],
            ['OTFHVKana', false],
            ['OTFProportionalMetrics', false],
            ['OTFRomanItalics', false],
            ['LeadingModel', 'LeadingModelAkiBelow'],
            ['ScaleAffectsLineHeight', false],
            ['ParagraphGyoudori', false],
            ['CjkGridTracking', false],
            ['GlyphForm', 'None'],
            ['RubyAutoTcyDigits', 0],
            ['RubyAutoTcyIncludeRoman', false],
            ['RubyAutoTcyAutoScale', true],
            ['TreatIdeographicSpaceAsSpace', true],
            ['AllowArbitraryHyphenation', false],
            ['BulletsAndNumberingListType', 'NoList'],
            ['NumberingStartAt', 1],
            ['NumberingLevel', 1],
            ['NumberingContinue', true],
            ['NumberingApplyRestartPolicy', true],
            ['BulletsAlignment', 'LeftAlign'],
            ['NumberingAlignment', 'LeftAlign'],
            ['NumberingExpression', "^#.^t"],
            ['BulletsTextAfter', "^t"],
            ['ParagraphBorderLeftOffset', 0],
            ['ParagraphBorderRightOffset', 0],
            ['ParagraphBorderTopOffset', 0],
            ['ParagraphBorderBottomOffset', 0],
            ['ParagraphBorderStrokeEndJoin', 'MiterEndJoin'],
            ['ParagraphBorderTopLeftCornerOption', 'None'],
            ['ParagraphBorderTopRightCornerOption', 'None'],
            ['ParagraphBorderBottomLeftCornerOption', 'None'],
            ['ParagraphBorderBottomRightCornerOption', 'None'],
            ['ParagraphBorderTopLeftCornerRadius', 12],
            ['ParagraphBorderTopRightCornerRadius', 12],
            ['ParagraphBorderBottomLeftCornerRadius', 12],
            ['ParagraphBorderBottomRightCornerRadius', 12],
            ['ParagraphShadingTopLeftCornerOption', 'None'],
            ['ParagraphShadingTopRightCornerOption', 'None'],
            ['ParagraphShadingBottomLeftCornerOption', 'None'],
            ['ParagraphShadingBottomRightCornerOption', 'None'],
            ['ParagraphShadingTopLeftCornerRadius', 12],
            ['ParagraphShadingTopRightCornerRadius', 12],
            ['ParagraphShadingBottomLeftCornerRadius', 12],
            ['ParagraphShadingBottomRightCornerRadius', 12],
            ['ParagraphBorderStrokeEndCap', 'ButtEndCap'],
            ['ParagraphBorderWidth', 'ColumnWidth'],
            ['ParagraphBorderTopOrigin', 'AscentTopOrigin'],
            ['ParagraphBorderBottomOrigin', 'DescentBottomOrigin'],
            ['ParagraphBorderTopLineWeight', 1],
            ['ParagraphBorderBottomLineWeight', 1],
            ['ParagraphBorderLeftLineWeight', 1],
            ['ParagraphBorderRightLineWeight', 1],
            ['ParagraphBorderDisplayIfSplits', false],
            ['MergeConsecutiveParaBorders', true],
            ['ProviderHyphenationStyle', 'HyphAll'],
            ['DigitsType', 'DefaultDigits'],
            ['Kashidas', 'DefaultKashidas'],
            ['DiacriticPosition', 'OpentypePositionFromBaseline'],
            ['CharacterDirection', 'DefaultDirection'],
            ['ParagraphDirection', 'LeftToRightDirection'],
            ['ParagraphJustification', 'DefaultJustification'],
            ['ParagraphKashidaWidth', 2],
            ['XOffsetDiacritic', 0],
            ['YOffsetDiacritic', 0],
            ['OTFOverlapSwash', false],
            ['OTFStylisticAlternate', false],
            ['OTFJustificationAlternate', false],
            ['OTFStretchedAlternate', false],
            ['KeyboardDirection', 'DefaultDirection']
          ],
          properties: [
            { tag: "Leading", attrs: [['type', 'enumeration']], text: 'Auto' },
            { tag: 'TabList', attrs: [['type', 'List']], text: '' },
            { tag: "AppliedFont", attrs: [['type', 'string']], text: 'Arial' },
            { tag: "RuleAboveColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "RuleBelowColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "RuleAboveType", attrs: [['type', 'object']], text: 'StrokeStyle/$ID/Solid' },
            { tag: "RuleBelowType", attrs: [['type', 'object']], text: 'StrokeStyle/$ID/Solid' },
            { tag: "BalanceRaggedLines", attrs: [['type', 'enumeration']], text: 'NoBalancing' },
            { tag: "RuleAboveGapColor", attrs: [['type', 'object']], text: 'Swatch/None' },
            { tag: "RuleBelowGapColor", attrs: [['type', 'object']], text: 'Swatch/None' },
            { tag: "UnderlineColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "UnderlineGapColor", attrs: [['type', 'object']], text: 'Swatch/None' },
            { tag: "UnderlineType", attrs: [['type', 'object']], text: 'StrokeStyle/$ID/Solid' },
            { tag: "StrikeThroughColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "StrikeThroughGapColor", attrs: [['type', 'object']], text: 'Swatch/None' },
            { tag: "StrikeThroughType", attrs: [['type', 'object']], text: 'StrokeStyle/$ID/Solid' },
            { tag: "SpanSplitColumnCount", attrs: [['type', 'enumeration']], text: 'All' },
            { tag: "ParagraphShadingColor", attrs: [['type', 'object']], text: 'Color/Black' },
            { tag: "ParagraphBorderColor", attrs: [['type', 'object']], text: 'Color/Black' },
            { tag: "ParagraphBorderGapColor", attrs: [['type', 'object']], text: 'Swatch/None' },
            { tag: "ParagraphBorderType", attrs: [['type', 'object']], text: 'StrokeStyle/$ID/Solid' },
            { tag: "Mojikumi", attrs: [['type', 'enumeration']], text: 'Nothing' },
            { tag: "KinsokuSet", attrs: [['type', 'enumeration']], text: 'Nothing' },
            { tag: "RubyFont", attrs: [['type', 'string']], text: '$ID/' },
            { tag: "RubyFontStyle", attrs: [['type', 'enumeration']], text: 'Nothing' },
            { tag: "RubyFill", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "RubyStroke", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "KentenFont", attrs: [['type', 'string']], text: '$ID/' },
            { tag: "KentenFontStyle", attrs: [['type', 'enumeration']], text: 'Nothing' },
            { tag: "KentenFillColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "KentenStrokeColor", attrs: [['type', 'string']], text: 'Text Color' },
            { tag: "BulletChar", attrs: [['BulletCharacterType', 'UnicodeOnly'], ['BulletCharacterValue', '8226']], text: '' },
            { tag: "NumberingFormat", attrs: [['type', 'string']], text: '1, 2, 3, 4...' },
            { tag: "BulletsFont", attrs: [['type', 'string']], text: '$ID/' },
            { tag: "BulletsFontStyle", attrs: [['type', 'enumeration']], text: 'Nothing' },
            { tag: "AppliedNumberingList", attrs: [['type', 'object']], text: 'NumberingList/$ID/[Default]' },
            { tag: "NumberingRestartPolicies", attrs: [['RestartPolicy', 'AnyPreviousLevel'], ['LowerLevel', 0], ['UpperLevel', 0]], text: '' },
            { tag: "BulletsCharacterStyle", attrs: [['type', 'object']], text: 'CharacterStyle/$ID/[No character style]' },
            { tag: "NumberingCharacterStyle", attrs: [['type', 'object']], text: 'CharacterStyle/$ID/[No character style]' },
            { tag: "SameParaStyleSpacing", attrs: [['type', 'enumeration']], text: 'SetIgnore' },
          ]
        },
        // Paragraphe défini  
        {
          attrs: [
            ['Self', "ParagraphStyle/$ID/[No paragraph style]"],
            ['Name', "$ID/[No paragraph style]"],
            ['Imported', 'false'],
            ['NextStyle', 'ParagraphStyle/$ID/NormalParagraphStyle'],
            ['SplitDocument', 'false'],
            ['EmitCss', 'true'],
            ['StyleUniqueId', '1bb95230-9e5d-47f6-a61d-b6702815a69d'],
            ['IncludeClass', 'true'],
            ['ExtendedKeyboardShortcut', '0 0 0'],
            ['EmptyNestedStyles', 'true'],
            ['KeyboardShortcut', '0 0'],
          ],
          properties: [
            { tag: "BasedOn", attrs: [['type', 'string']], text: '$ID/[No paragraph style]' },
            { tag: "PreviewColor", attrs: [['type', 'enumeration']], text: 'Nothing' },
          ]
        }
      ],
      attrs: [['Self', IDML.generateId()]]
    },
    {
      tag: 'TOCStyle',
      attrs: [
        ['Self', 'TOCStyle/$ID/DefaultTOCStyleName'],
        ['TitleStyle', 'ParagraphStyle/$ID/[No paragraph style]'],
        ['Title', 'Table des matières'],
        ['Name', '$ID/DefaultTOCStyleName'],
        ['RunIn', false],
        ['IncludeHidden', false],
        ['IncludeBookDocuments', false],
        ['CreateBookmarks', true],
        ['SetStoryDirection', 'Horizontal'],
        ['NumberedParagraphs', 'IncludeFullParagraph'],
        ['RemoveForcedLineBreak', false],
        ['MakeAnchor', false],
      ]
    },
    {
      tag: 'RootCellStyleGroup',
      children: [],
      attrs: [['Self', IDML.generateId()]]
    },
    {
      tag: 'RootTableStyleGroup',
      children: [],
      attrs: [['Self', IDML.generateId()]]
    },
    {
      tag: 'RootObjectStyleGroup',
      children: [],
      attrs: [['Self', IDML.generateId()]]
    },
    {
      tag: 'TrapPreset',
      items: [
        // {text: '...', attrs: [], ns: '...'}
        {
          text: "",
          attrs: [
            ['Self', 'TrapPreset/$ID/k[No Trap Preset]'],
            ['Name', '$ID/k[No Trap Preset]'],
            ['DefaultTrapWidth', '0.25'],
            ['BlackWidth', '0.5'],
            ['TrapJoin', 'MiterEndJoin'],
            ['TrapEnd', 'MiterTrapEnds'],
            ['ObjectsToImages', true],
            ['ImagesToImages', true],
            ['InternalImages', false],
            ['OneBitImages', true],
            ['ImagePlacement', 'CenterEdges'],
            ['StepThreshold', 10],
            ['BlackColorThreshold', 100],
            ['BlackDensity', '1.6'],
            ['SlidingTrapThreshold', 70],
            ['ColorReduction', 100],
          ]
        },
        {
          text: "",
          attrs: [
            ['Self', 'TrapPreset/$ID/kDefaultTrapStyleName'],
            ['Name', '$ID/kDefaultTrapStyleName'],
            ['DefaultTrapWidth', '0.25'],
            ['BlackWidth', '0.5'],
            ['TrapJoin', 'MiterEndJoin'],
            ['TrapEnd', 'MiterTrapEnds'],
            ['ObjectsToImages', true],
            ['ImagesToImages', true],
            ['InternalImages', false],
            ['OneBitImages', true],
            ['ImagePlacement', 'CenterEdges'],
            ['StepThreshold', 10],
            ['BlackColorThreshold', 100],
            ['BlackDensity', '1.6'],
            ['SlidingTrapThreshold', 70],
            ['ColorReduction', 100],
          ]
        }
      ]
    }
  ]
} as XMLObjet;