---
id: book1 # l'identifiant unique du livre
document: # Tout ce qui concerne le document
  height: 297 #mm
  width: 210 #mm
  bleed: 3 #mm fond perdu
  Tmargin: 20 #mm
  Bmargin: 20 #mm
  Lmargin: 15 #mm
  Rmargin: 15 #mm
  Imargin: 15 #mm Marge intérieure (si double page)
  EMargin: 10 #mm Marge extérieure (si double page)